// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ballot_box

import (
	"github.com/danielchiovitti/ballot-box/pkg/database/provider"
	"github.com/danielchiovitti/ballot-box/pkg/presentation"
	"github.com/danielchiovitti/ballot-box/pkg/presentation/factory/usecase/redis"
	"github.com/danielchiovitti/ballot-box/pkg/presentation/factory/usecase/redisbloom"
	"github.com/danielchiovitti/ballot-box/pkg/presentation/route"
	"github.com/danielchiovitti/ballot-box/pkg/shared"
	"github.com/google/wire"
	redis2 "github.com/redis/go-redis/v9"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func InitializeHandler() *presentation.Handler {
	healthRoute := route.NewHealthRoute()
	votingRoute := route.NewVotingRoute()
	viper := NewViper()
	redisProvider := provider.NewRedisProvider(viper)
	client := NewRedisClient(redisProvider)
	setUseCaseFactoryInterface := redis.NewSetUseCaseFactory(client)
	configInterface := shared.NewConfig(viper)
	handler := presentation.NewHandler(healthRoute, votingRoute, viper, setUseCaseFactoryInterface, configInterface)
	return handler
}

// wire.go:

func NewViper() *viper.Viper {
	v := viper.New()
	v.SetEnvPrefix("bb")
	v.AutomaticEnv()
	return v
}

func NewRedisClient(r *provider.RedisProvider) *redis2.Client {
	res, _ := r.GetRedisClient()
	return res
}

var superSet = wire.NewSet(
	NewViper, shared.NewConfig, provider.NewRedisProvider, NewRedisClient, provider.NewRedisBloomProvider, presentation.NewHandler, route.NewHealthRoute, route.NewVotingRoute, provider.NewMongoDbProvider, redis.NewIncrUseCaseFactory, redis.NewExpireUseCaseFactory, redisbloom.NewReserveUseCaseFactory, redisbloom.NewAddUseCaseFactory, redisbloom.NewExistsUseCaseFactory, redis.NewGetUseCaseFactory, redis.NewSetUseCaseFactory,
)
